### ISSUE TITLE
Format upon build

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1005]
Not Reason proper, but very related. A frequent problem I've encountered when receiving external contributions is that people don't manually call `refmt`, through their editor or otherwise, when submitting changes. READMEs don't help.

I'm wondering if we can just (optionally) format the whole file at each build call. This requires build system hooks (cc @bobzhang), but in general I'd like to push editor-level tooling down to lower-level (see #993). This also leaves less to maintain for editor integration authors like @freebroccolo and others.

**Comment by jordwalke** [comment]
I've heard this feedback too. Here's something we can actually do without much invasive work in build systems, and without stepping on peoples' files under them in their editor. What do you think about this:

- Have `-pp refmt` not only parse into an AST, but then also secretly *print* the file and compare it to the original. If it's different, as a final step, it could inject an extension point warning that may block the build (or perhaps we have it *not* block the build).
- We could make it only behave this way in DEV mode, so production builds and builds as a dependency are not slowed down.
- The warning could have a message like this printed to the console (or merlin):

   > Warning: Your file is not formatted according to convention.
   > Run the following command to format it:
   >  `refmt /path/to/myFile.re -print .re > /path/to/myFile.re`

The benefit of this approach is that it requires no intervention from build systems (no work for BuckleScript), and doesn't clober files out from under you.

I would also have printing store an AST attribute like `[@refmt width = 120]` at the top of the file when printing to text so that it automatically detects the last-used width without having to supply it on the command line.

**Comment by chenglou** [comment]
Btw your unix command would erase the file, remember? =P

It's nice not needing build system intervention, but your solution (step 1) still requires manual calling of `refmt` in the editor/terminal?

**Comment by jordwalke** [comment]
@chenglou Okay imagine something like:

```
./fixMyFiles.sh
```

And it wouldn't be needed if you just run the formatter from within the editor.
Clobbering source files can be really bad and much worse than making people run a command line command or key command in their editor. For example if you undo, undo, undo, and then something clobbers the file contents in a source file, it destroys the redo stack! (Except in Vim, naturally).

**Comment by chenglou** [comment]
Right, but my point was to remove the manual and editor-level need of calling refmt. Such build system behavior would be opt-in or opt-out btw.

> if you undo, undo, undo, and then something clobbers the file contents in a source file, it destroys the redo stack!

That's true, yeah. But we can still make it opt-in/opt-out.

**Comment by bsansouci** [comment]
I want to believe that you could use Travis to `refmt` the code in the PR and diff it against the original code to make sure nothing changed.
This would only work with projects that can afford to have something like Travis though.

Since we want the least amount of commands to be ran, and the user still has to run the build command (or watch), I think it wouldn't be so bad to add it to the build system.

**Comment by tekknolagi** [comment]
@chenglou @jordwalke the unix command can use the new `--in-place` flag!

**Comment by chenglou** [comment]
@bobzhang would it be possible to expose a onFileChange hook in bsb? I'm thinking that it's probably not possible to have it in Ninja? What about in the watcher?

cc @rickyvetter

**Comment by bobzhang** [comment]
I worry that it would have race conditions with editors

**Comment by chenglou** [comment]
How so? Btw it'll be opt-in

**Comment by bobzhang** [comment]
Since both editors and build systems are writing you me files

**Comment by chenglou** [comment]
If you don't save a file, the watcher wouldn't detect the change right?
To be clear, I'm thinking to have this at the watcher level. More performant. Otherwise the build system would have to know which files you've changed, change them again, then start the build. That's what I meant by ninja maybe not supporting such thing.

Save file -> trigger watcher -> trigger save (either through watcher, or build system pre-build hook) -> format -> build

**Comment by bobzhang** [comment]
it is not that simple, since there would be delay, then it would cause concurrency and race condition

**Comment by freebroccolo** [comment]
I may be missing something but I think the only way you could avoid what @bobzhang is describing would be to lock the editor document for the file to be reformatted until the operation is finished. Otherwise, even if you force a save of the document, the user might make another edit before the reformatted content is returned.

In the case of vscode, it will complain loudly if the document is dirty and the file has also been changed outside of the editor (because the two might have diverged). It will refuse to let you save the document again until you jump through several hoops. And I don't even think it's possible to lock the document with the current API, at least not in a clean way.

**Comment by chenglou** [comment]
Sigh, just tested this workflow. Vim can't update this correctly without installing an external plugin, and atom occasionally craps out and resets the cursor to line 0 when the file's long (long for atom, aka 400 lines). Guess we can't have this =|

Thanks for the feedback folks!

**Comment by rickyvetter** [comment]
Woah I really think this is a premature close here. Elm has this working on [Atom](https://github.com/triforkse/atom-elm-format/blob/master/src/index.js#L71-L73), [Vim (without extra deps)](https://github.com/ElmCast/elm-vim/blob/b47d013d1fdfecc9e19df8034439b8e379813696/ftplugin/elm.vim#L67-L72), [VS Code](https://github.com/sbrink/vscode-elm/blob/8d05c4734b7affa6307ff2d94ad78e095718462b/src/elmFormat.ts#L33-L45) and [others](https://github.com/avh4/elm-format#editor-integration). I get that this behavior could potentially be problematic, but as an opt in feature for projects with multiple contributors this seems like it's worth pursuing.

**Comment by freebroccolo** [comment]
For the record, the latest release of the Reason vscode plugin supports format-on-save as an option. That part is not problematic. The difficulty is being able to support format-on-build given the asynchronous nature of editing.

For vscode, format-on-build support would require being able to lock the document (or rather all of the documents being built) until after the build finishes. I think that in practice this would make for a pretty awkward workflow even if one could do it with the current API (currently there is no support for locking documents like this).

The only potential workaround I see for that would be to cause a build to trigger a save, then listen for the save event and stall until the build finishes. That might work, assuming that builds complete quickly enough, but part of it would have to be done synchronously (which could case lag or other issues) and it would also interfere with other save operations.

I do think that having format-on-build support is good for external tooling (especially for CI and code review stuff) but I don't think it's the right fit many editor architectures. The reality is that supporting something like this in vscode would be significantly more work and less reliable than the current approach of just calling `refmt` when needed.

**Comment by rickyvetter** [comment]
Ahhh - my mistake. I wasn't thinking of the differences between formatting on save and on build. Makes sense to me.

**Comment by chenglou** [comment]
One day editors will hot reload correctly without losing cursor!
