### ISSUE TITLE
Punning for single field record

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1034]
Not the first time people trip on `{foo}` and wonder why it doesn't work. What can we do here? Too many conflicts for just `{foo}`

**Comment by bsansouci** [comment]
cc @Schmavery.

One idea that Avery had (correct me if I'm getting this wrong) was to make punning `{:foo, :bar}` instead of `{foo, bar}`. That would help disambiguate `{foo}` because you'd write `{:foo}` (could also be `{foo:}`).
This synergizes well with @jordwalke's named args proposal which uses `:` everywhere :p

**Comment by chenglou** [comment]
Synergizes or confuses?

**Comment by bsansouci** [comment]
Not sure where you could confuse function call and record literal punning. It would (1) remove the ambiguity of the one punned field case and (2) help when refactoring a record that was previously punned.
Real world example: 
`let a = {x, y: y - 10};` 
updated to 
`let a = {x - 10, y: y - 10}`

Took me a while to figure out why there was a syntax error.

Whereas if I were looking at `let a = {:x, y: y - 10};` I wouldn't be tempted to do `let a = {:a - 10, y: y - 10}` without updating the first key.

Now that I think about it though, the named args with `:punnedArg` could be confusing in this case:
`{someField: someFunc :namedArg}`, not sure.
(Actually: https://gist.github.com/jordwalke/119fb44b95fdf7d703041f8ac54b5b4e#file-named-rs-L132).

**Comment by jordwalke** [comment]
We currently have a way to distinguish single field punned records from single "statement" expressions in `{}`, but perhaps our tooling doesn't make good use of it. 

@yunxing Mentioned that we could require the final sequence item to have `;`, which resolves this case. Our tooling would need to do a better job of enforcing it at print time.

```reason
let x = {
  y
};
/* vs. */
let x = {
  y;
};
```

**Comment by jordwalke** [comment]
Does anyone have any other proposals that they like more than the above one?

**Comment by glennsl** [comment]
I'd prefer a solution more along the lines of what @Schmavery/@bsansouci proposed if possible, since it's much more explicit (as long as it doesn't clash with something else, of course). But despite its subtleness, requiring semicolon is a solution I consider firmly in the "good enough for now" category.

**Comment by jordwalke** [comment]
@Schmavery / @bsansouci proposal has a symmetry with the current punned named args syntax. On the other hand, it's less familiar, not just to JS developers but to ML developers.

**Comment by glennsl** [comment]
It may be less familiar, but it's also much less of a hidden trap. It's a feature that can be discovered and looked up before falling into said trap. Not that the proposal isn't without other issues, as have been pointed out, and as I said I think semicolons are certainly good enough for now. But all else being equal, I'd take eliminating traps over familiarity any day of the week.

Btw, I think the Rust developers had some very interesting thoughts on this topic recently: https://blog.rust-lang.org/2017/03/02/lang-ergonomics.html

**Comment by hcarty** [comment]
_Please please please_ don't make trailing `;` significant in distinguishing between these two syntactic forms.  It's very nice to be able to have a trailing `;` in records to ease future editing.  It's nice to elide a `;` from the last portion of an expression since that's the result of the surrounding expression.  The `;` rules in Reason are already rather difficult to track and explain to new users.

**Comment by hcarty** [comment]
FWIW, if function application syntax becomes parenthesized (`f(a, b)` vs `foo a b`) then the ambiguity of a `:` prefix goes away.

**Comment by anmonteiro** [comment]
I think this is now outdated.
