### ISSUE TITLE
refmt dies on Arg.[]

### ISSUE THREAD

**Issue by sgrove** [facebook/reason#1119]
According to @hcarty

> `Arg.[]` is a list literal with Arg opened inside of the list (another form of local open)

`refmt` dies on this however:

```
$ echo "Arg.[]" | refmt
File "", line 1, characters 5-6:
Error: 2133: <SYNTAX ERROR>
```

Wrapping extra parens in the (valid) ML version helps though (when doesn't it, really? 😄 ):

```
$ echo "Arg.([])" | refmt
Arg.([]);
```

**Comment by SanderSpies** [comment]
As just discussed in the Discord channel this is apparently due to using 4.02.3 which doesn't have support for this yet. When I run this code with Reason + OCaml 4.04.0 it works. 

This feature was introduced in 4.03: https://github.com/ocaml/ocaml/commit/33769079299fdc3e0e89a33efa9c753412899963

More interesting though is that three people stumbled on this already (you, @andreas and @fson).

**Comment by spicydonuts** [comment]
I tried updating to `4.03` (and `4.04.1`) and still have this issue, but I also have no idea what I'm doing so I may not have updated correctly. (`opam switch` then `opam install reason`, though I had to use `opam install ocamlfind.1.7.1 reason` to actually get either to build).

**Comment by anmonteiro** [comment]
This was fixed in https://github.com/facebook/reason/pull/2043

**Comment by sgrove** [comment]
Was this ever released to OPAM?

**Comment by IwanKaramazow** [comment]
Unfortunately it wasn't. How quick do you need a release on opam?
