### ISSUE TITLE
js primitive comparison : list/array confusion

### ISSUE THREAD

**Issue by giraud** [facebook/reason#1122]
Reading the basic language primitives section of https://facebook.github.io/reason/javaScriptCompared.html, 
it's not clear that `[1, 2, 3]` is a list representation and is converted to 
```rust
var x = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];
```

for optimisations.

Maybe the array notation `[| 1, 2, 3 |]` should be also mentioned.

**Comment by neonsquare** [comment]
There are actually two things that play a role in this case:

1) OCaml heritage vs. JS heritage
In OCaml [1,2,3] has list semantics while [|1,2,3|] has array semantics. In JS there is no list type but just arrays. On the other side: Many JS libraries are using JS arrays as lists with operations like lodash.tail (actually [1,2,3].slice(1)).

The Reason syntax is a mix between OCaml and JS - it is not immediately clear if [1,2,3] may be better handled as an array or a list.

Pro array:
Index accesses to lists are O(n) - so people could think this should be O(1).

Pro list:
Operations like tail accesses are non-consing. So people who used JS in a more functional oriented style may even get better performance out of using really OCaml lists instead of arrays.

The question is here... which of those things is more likely? People expecting array performance/semantics or people using list semantics like in JS anyway.

2) Bucklescript and JS interaction

Where it actually plays a bigger role is when compiling using Bucklescript. If you create an JS obj like this:

[%bs.obj {foo : [1,2,3]}]

it actually will be:

{foo : [1, [2, [3, []]]]}

so one needs OCaml syntax:

[%bs.obj {foo: [|1,2,3|]}]

to get
{foo: [1,2,3]}

If Reasons array syntax would be [1,2,3] this Bucklescript ffi case would be closer to the target representation.

**Comment by bobzhang** [comment]
note with recent reason syntax you can write

```re
{ "foo" : [|1,2,3 |]}
```

which you get output

```js
{ foo : [1,2,3]}
```
so we are only one step from getting typed json object

**Comment by chenglou** [comment]
Documented properly now.
