### ISSUE TITLE
Suggested syntax improvements: Tuples and ES6 Calling Syntax.

### ISSUE THREAD

**Issue by bobzhang** [facebook/reason#1184]
Note I don't have opinions in syntax in general, but syntaxes proposed below I think will have a huge benefit to BuckleScript users (yet not hurt native users either), see relevant discussions in #722

1. Replace Tuple syntax from `()` to `[]`
Reasons: `()` is widely used in almost all languages for function call, using `()` for tuple will introduces a lot of ambiguity, there is some ugly part in current OCaml, you can not write
```
( x : int, y : int)
```
with this change, you can write
```
[ x : int , y : string ]
```
Another benefit is that Tuple `[1,2]` is literally compiled into `[1,2]` in JS (via BuckleScript), it is immutable also, which is better for FFI, List notation can be replaced with `[< >]`
2. `int * string` is replaced by  `[int, string]`
You can even say tuples are just label-less record.
3. Closed function application `f(.x,y)`
It is ` f x y [@bs]` which means closed application

4. Use `function` for uncurried function
`function (a0,a1,a2) => body` is translated to `fun [@bs] a0 a1 a2 -> body` in ocaml

5. ` int => int => int [@bs]` is replaced by ` (. int, int ) => int`

Disclaimer: I am not sure it will introduce conflicts or not.

**Comment by jordwalke** [comment]
### Brackets `[ , ]` as Tuple:
> Replace Tuple syntax from () to []
Reasons: () is widely used in almost all languages for function call, using () for tuple will introduces a lot of ambiguity, there is some ugly part in current OCaml, you can not write `( x : int, y : int)`

This was one of the things that we fixed in Reason. In Reason, *can* in fact write `(10 : int, 20 : int)`. The proposed syntax you suggested also has that positive property, but I would just point out that we do already enjoy the fix in Reason. (I've learned that the reason why OCaml's syntax has this ambiguity is that `,` is actually an *infix* token that forms the tuple). 


> Another benefit is that Tuple [1,2] is literally compiled into [1,2] in JS (via BuckleScript), it is immutable also.

Curious, doesn't the current Reason tuple syntax also have the positive properties of being compiled into an immutable structure? The benefit of `[x, y]` specifically seems to be more that the JS representation matches what you write in Reason exactly, correct?

> int * string is replaced by [int, string]

In general, it makes sense that type definitions resemble the structure of the values. We fixed the `x * y` syntax in Reason for exactly that reason as well. In Reason, it's `let x : (int, string) = (2, "hi")`. It would indeed make sense to maintain that symmetry even if tuples were represented as `[x, y]` (so `let x : [int, string] = [10, "hi"]`).


> Closed function application `f(.x,y)`  It is `f x y [@bs]` which means closed application

Just so I understand. Would that only be for external function application?

### JS Calling Syntax:
Relatedly, I am also interested in seeing if the JS calling syntax can be achieved for applying curried function arguments. The downside with tuples as they exist today, is that you have to then do `myFunc((x, y))` when passing a single tuple - which looks strange perhaps.

The main reason I'm interested in a tuple syntax form of `[x, y]` (or something similar) is because it allows adopting of a paren based JS application syntax, while still allowing omission of parenthesis when passing a single "simple" argument to a function. I do like the JS style multi-argument calling syntax, however I do not like it when passing a single record argument for example. The first example below *feels* more like React has the power to extend the language by simply defining the `create` function (I know it's not really extending the language, but omitting the parens in this case creates a similar experience). 

```reason
/* I like this better */
let button = React.create {
};
/* ... than this */
let button = React.create ({
});

/* However when applying multiple arguments I don't mind this */
let res = React.render(intoThisNode, someComponent);
```

I don't believe it is possible to have both JS calling syntax, *and* this ability to *optionally* omit the parens around single arguments, unless we *also* change the tuple syntax. It's now not just a matter of `someFunction((x, y))` being ugly - it's worse. `someFunction(x, y)` is then ambiguous. Is it a single tuple argument passed to `someFunction` where we omitted the parens, or is it applying multiple arguments to a curried function? Changing the tuple syntax does fix that:

```reason
/* Apply two arguments two curried function */
someFunction ({x: hi}, b);
/* Now with the first argument being a tuple */
someFunction ([x, y], b);
/* Apply a single argument to that same curried function */
someFunction  {x: hi};
/* Now with that first argument being a tuple */
someFunction  [x, y];
```

### Other Alternatives To `[ , ]` and `( , )`
The only downside with using `[ ]` to represent tuples, is that JS programmers immediately know what `[hd, ...tl]` means some kind of "extension" - be it list concat or list append. It is nice that the language construct that Reason choses `[ ]` for *also* has *some* notion of extension `...`.

There's another nice aspect of using `()` at the "edges" of tuples. That is that there is no concept of a single item tuple. Therefore `(x + 1)` is always unambiguous and without wasting any syntactic real estate. Whereas if `[]` represented tuples, `[x + 1]` would be somewhat of a "waste" of real estate since it would be parsed as `(x + 1)` and adds no additional information. If `[]` represents something else like lists, then `[x + 1]` does not waste any scarce syntactic real estate as it has meaning (list with one item).

By choosing another clever syntax for tuples. I believe that we can achieve everything that I said was desirable, as well as almost *everything* you said you wished for (including allowing JS calling convention - and closed calling syntax). For example, I'm just using pipe `|` as a placeholder here, but it demonstrates that a separate infix token can accomplish most of the goals.

```reason
type stringAndIntTuple = (string | int);
let myTuple = ("hello" | 234);
someFunction ((x | y), b);  /* Calling with multiple arguments */
someFunction (x | y);       /* Passing a single tuple */
```

There are many options besides `|`. The `&` symbol would be even more fitting, and with `Reason`.

Note that changing the calling syntax requires a bit more work before we are ready.

```reason
let something = myThing.foo(1, 3).bar();
/* Is currently parsed as */
let something = (myThing.foo) ((1, 3).bar())
/* We need to change that ^^^ */
/*Also, need to unify "unary" precedence with ! precedence making
 * them both unary - in order for ! to behave like people expect it to */
```

**Comment by jordwalke** [comment]
Thanks for bringing this up, by the way. I've been meaning to get all the considerations down in writing.

**Comment by SanderSpies** [comment]
I would prefer to keep the current tuple syntax as-is. I'm not aware of another popular form that we could use. I would not mind giving up the ES6 single argument form for this.

**Comment by cristianoc** [comment]
@jordwalke One could use another clever syntax (infix) for tuples, or another clever syntax for application, to indicate passing several arguments at once:
```
someFunction (x, y);       /* Passing a single tuple */
someFunction (x | y);       /* Passing two arguments */
```

**Comment by jordwalke** [comment]
@cristianoc Yes, that would work. I actually think the infix syntax of `&` makes a lot of sense since we currently have "or" patterns represented with `|` - and what are tuples but *and* patterns?

```rust
type eitherOr 't =
  | Either 't
  | Or 't;
type tuple 't = ('t & 't);

let (Either v | Or v) = Either "hello";
let (v1 & v2) = (10, "hi");
```

**Comment by kennetpostigo** [comment]
Coming from Javascript with no prior ML background I found that the consistency between typing and creating values of a certain type were really useful in reason. It is slightly confusing at first when there is no `()` for calling a function but it sticks relatively quickly. I would really hate it if List notation got changed to `[<>]` and Tuples got `[]`. @jordwalke I kind of like your approach quite a bit. That would open up calling functions to this `invokeMe("yes", "please")`?

**Comment by bobzhang** [comment]
1. Note I suggest changing tuple from `()` into `[]` is due to  `()` is overloaded in many use cases, it is not a tuple here: ` ( 1 + 2 ) * 2 `. Actually a singleton tuple is quite consistent with record (unboxed).  you can make uncurried function even shorter (without function keyword)
```reason
let f = (x,y) => x + y ; (*  uncurried `f`  *)
```
2. Uncurried  calling convention support  is really important, there are so many times I want to patch the parser of the compiler to support it natively. **_It is used everywhere, not just FFI_** (see https://github.com/neonsquare/bucklescript-benchmark/pull/1).
3. Given similar syntax but different semantics is quite misleading, currently reason `[x , ... xs]` are not really the same as `[x, ... xs ]` in any way, and list data structure  is rarely useful in real world.

My least wish is that Reason could provide native syntax for uncurried calling convention (#2)

**Comment by bobzhang** [comment]
>The benefit of [x, y] specifically seems to be more that the JS representation matches what you write in Reason exactly, correct?

Yes, and it is consistent with typescript which is quite important (maybe flow too)

```
// Declare a tuple type
let x: [string, number];
// Initialize it
x = ["hello", 10]; // OK
```

> Would that only be for external function application?

No, it is used everywhere as callback when you care about perf

I would be very happy to like Reason syntax more than vanilla OCaml syntax if my wishes are fullfilled, since it will deliver significant values to BuckleScript users

**Comment by bobzhang** [comment]
I don't understand why TC39 introduce `[ hd, ... tl ]`, this is a horrible idea, it literally encourages in-efficient style, sometimes, I really feel sorry for JS VM developers, they work so hard to improve the JS performance

**Comment by bobzhang** [comment]
Maybe we can leave curried syntax as is (since it indeed has different semantics from JS function call), but BuckleScript uncurried calling convention has exactly the same semantics as JS calling convention, it makes sense to have the same semantics

**Comment by bobzhang** [comment]
btw, having `[]` as tuple actually will make React-JS bindings easier, in your ppx, you can delegate bindings to `createElementChildren2`, `createElementChildren3`,.. `createElementChildrenN`, it is more efficient (no copy) and more flexibly, no longer need to make it homegenous

**Comment by dogfishbar** [comment]
OCaml syntax has its problems, e.g., the braces in Reason's `switch e { ... cases ...}` are helpful. But as an OCaml programmer with a background in lambda calculus, I have to say, the designers of OCaml did a good job with their concrete syntax for function application, tupling, pattern matching and most importantly staying faithful to the mathematical tradition of using parentheses for grouping. Most of the LC-based languages that I know of do the same thing because they thought carefully about orthogonality and arrived at the same conclusion.
The tupling operator is an infix comma `1, 2, 3`. The function application operator is an infix whitespace `f x`. Programmers can parenthesize these as `(1, 2, 3)` or `(f x)` if they want or need to just as they can write `1 + 2 + 3` as `(1 + 2) + 3`. 
The **great idea** here that **you really should keep** in Reason is that the combination of curried functions + pattern matching + comma-separated-tuples is very flexible and allows for JS-style "multi-argument" functions. `let add = (x, y) => x + y` or `let add(x, y) = x + y` can be applied as in `add(n1, n2)`. I think it's a terrible mistake to specify that the `(x, y, z)` in `(x, y, z) => ...` is anything other than a pattern matching a triple.

**Comment by jordwalke** [comment]
> But the designers of OCaml did a good job with their concrete syntax for function application, tupling, pattern matching and most importantly sticking with the mathematical tradition of using parentheses for grouping

Except for variants, where there is not only an ambiguity, but where the infix comma `,` doesn't represent tuppling, but applying multiple arguments to a non-curried constructor.

**Comment by dogfishbar** [comment]
OK, fair enough. I wasn't thinking of the wrinkles with variants in OCaml.
(I prefer the Elm approach for this but I don't know the typing issues.)
But my point still stands: if you want to a variation of OCaml that's more
accessible to JS programmers why not extend the parser to allow optional
explicit types for tuple patterns? A JS programmer would surely be good to
go with:

let f(x : int, y : float) = ...

Bob

**Comment by dc-mak** [comment]
Hello,

Take a look at the following image, and think about what the type of a line `f(x)` should be. I argue that most beginners and functional programmers would expect it to be `(int, string, bool)`, because `'a = int, 'b=string, 'c = bool`
![image](https://user-images.githubusercontent.com/7052028/37500146-ba3f10f6-28bf-11e8-8210-fd501b2ce40c.png)


[Strong FP/static types/OCaml background here, no JS experience, so please correct me where I am wrong]. I realise there has been much discussion with valid points and interesting ideas but I find the inconsistency in the image attached incomprehensible. The types match up visually (annotations are just ones inferred by editor/compiler shown explicitly to illustrate the problem) e.g. *visually* `f : 'a => 'b` and `x : 'a` but `¬ (f (x) : 'b)`. Explaining typed-function application to beginners can be difficult enough without a pretty-printer blending concepts together (e.g. `('a1,..'an) => 'd` as syntax sugar for `'a1 => ... => 'an => 'b`, what the latter means, how it is different from `('a1 * ... * 'an)` etc.).

By effectively hiding `'a1 => ... => 'an => 'b as (a1, ..., an) => b` (which, in and of itself, is understandable, even if I don't personally agree with it) you end up with a situation where
`('a,'b,'c) => ('a,'b,'c)` is not a special case of the identity function type `'a => 'a`, e.g. substitutivity goes out the window. I think the issue there is the difference between tuples as arguments `(('a,'b,'c))` and tuples as results: `('a,'b,'c)`.

Off the top of my head, I can think of three general approaches to resolve what I perceive to be a inconsistency.

**Proposal 1** match term-syntax with type-syntax. Either this `[...]` or `[<..>]` or `((...))`. Whatever it is, it should be (a) the same both sides of an arrow `=>` and (b) be clearly distinct from "arguments" `('a,'b,'c) => 'd`. Clearly the `((...))` would not be too great for "noise" in the types.

**Proposal 2** use `*` or `&` for type-syntax, continue using the same term-syntax for tuples. Sacrificing the term/type syntax symmetry doesn't seem like something people are too keen on. Also a problem: at the term-level, `*` is integer-multiplication, `|` and `&` are boolean operators.

**Proposal 3** stop hiding/sugaring `'a1 => ... => 'an => 'b as (a1, ..., an) => b`  (similarly for function abstraction and application). This is likely to be the least popular proposal, but the one that would remove most parentheses and tidy up some of the "noise" that's crept into the types.

This is the "answer".
![image](https://user-images.githubusercontent.com/7052028/37500160-d1a58b12-28bf-11e8-8089-a5b4426e8d19.png)
To get the arguably more intuitive answer, you need the following code which looks a lot like a no-op.
![image](https://user-images.githubusercontent.com/7052028/37500165-dc2d8af8-28bf-11e8-8814-a0af4ebf6df1.png)

**Comment by dogfishbar** [comment]
Greetings Dhruv. Thanks for the email. I agree. When I define

let swap(x, y) = (y, x)


I intend swap to be applied to a pair -- full stop. I stopped following
Reason when I came to understand that the authors were unalterably
committed to screwing up the concrete syntax of Currying. Such a huge
bummer, all for the temporary benefit of on-boarding JSers. They seem to
think that it won't be a problem. I disagree -- warts like this on
languages don't go away, they get rubbed raw over time and become a drag on
adoption. I'm using Elm instead.
Best,
Bob Muller
