### ISSUE TITLE
Getting started for JS devs is too confusing

### ISSUE THREAD

**Issue by shaneosullivan** [facebook/reason#1269]
Pulling in conversation from Discord as an issue:

Following the instructions for getting started as a JS dev on a clean system is too confusing in the docs.  They link to many places that are apparently not necessary, or perhaps some are.  Similar for editor tooling.

The passing test for this issue is:

Take a clean system and try to follow the instructions like a noob. Follow every link and follow those instructions. Iterate until this is under five minutes

**Comment by glennsl** [comment]
In particular, this bit in the Editor Setup section of the JS workflow: "See our tooling section for a descriptions of what you need to install and which editors we support." can be interpreted to imply that all the tools listed on the Tooling page need to be installed, which is rather unfortunate.

Another bit of feedback is that testing isn't covered, and when asking about it on Discord some ocaml unit test framework like ounit or alcotest was apparently recommended. Probably because the question didn't specifically mention it was for the js workflow. There should perhaps be an introductory page for both workflows that describes the difference between them, what's common and what's not.

**Comment by glennsl** [comment]
Another tidbit: There's too much footnote-y information interspersed in the actual instructions, leading to confusion about what's actually relevant to get started and what's auxillary and just nice-to-know. I think it's good information to have, but it should be clearly distinguished from the primary content, for example by making the proper footnotes or sidenotes.

**Comment by chenglou** [comment]
I think we're good with the new docs. Thanks for the feedback!
