### ISSUE TITLE
bad attribute formatting

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1293]
cc @IwanKaramazow 

Input:

```reason
type reactClass = ReasonReact.reactClass [@@ocaml.deprecated "ReactRe.reactClass got moved under ReasonReact.reactClass. Please codemod all the references of ReactRe.reactClass to it."];
```

Output:
```reason
type reactClass = ReasonReact.reactClass

  [@@ocaml.deprecated
    "ReactRe.reactClass got moved under ReasonReact.reactClass. Please codemod all the references of ReactRe.reactClass to it."
  ];

```

**Comment by jordwalke** [comment]
Let's see how this one is formatted with @let-def's changes.

**Comment by IwanKaramazow** [comment]
Should I submit a fix? What branch has let-def's changes?

**Comment by let-def** [comment]
This branch has the most recent changes: https://github.com/let-def/reason/tree/es6_fun-3/ .

Changes are quite profound and while parser is in a good state, the printer implements the language but the formatting is not so pretty yet. Maybe I can open a separate PR which details the changes in syntax so that we can discuss formatting (it is not clear to me how things should be formatted :), there is a large aesthetic part to talk about).

**Comment by chenglou** [comment]
```
[@ocaml.deprecated
  "ReactRe.reactClass got moved under ReasonReact.reactClass. Please codemod all the references of ReactRe.reactClass to it."
]
type reactClass = ReasonReact.reactClass;
```

Looks good!
