### ISSUE TITLE
@@bs.deriving accessors appears broken for single records

### ISSUE THREAD

**Issue by desmond-dsouza** [facebook/reason#1317]
When I do this:
![image](https://user-images.githubusercontent.com/4407158/27509409-d5c3a68a-58c1-11e7-8e2e-006feaef7ca2.png)
I get this:
![image](https://user-images.githubusercontent.com/4407158/27509411-de7e0ffe-58c1-11e7-8ed5-c0697f134601.png)
Note that I typed in `[@@bs.deriving {accessors}]`, and refmt rewrote it as above.

Was asked to file this as _single record punning_ issue.

**Comment by dippi** [comment]
I temporarily solved using `[@@bs.deriving {accessors, accessors}]`

**Comment by chenglou** [comment]
We don't have single-record punning, see the note here: https://reasonml.github.io/guide/language/record#syntax-shorthand

So you'd need to use `{accessors: accessors}`

It's the curse of using a more familiar syntax unfortunately. I'll leave this issue open so that we can somehow provide a better error message. Sorry for the trouble!

**Comment by chenglou** [comment]
Fixed. This is now accepted in BS:

```reason
type a =
  | A float int
[@@bs.deriving accessors];
```
