### ISSUE TITLE
Better dereference sugar

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1435]
Right now in master `foo.contents` has the sugar `foo^`, which is eeeeh, not ideal. It'd be nice if `*foo` was supported (might clash a lot), or that we at least change it to `^foo`. Not sure what the latter is supposed to evoke though; seems arbitrary.

**Comment by jaredly** [comment]
I'm looking into this

**Comment by jaredly** [comment]
Hmmmmmm I don't think `*` will work actually, because there's probably not a way to distinguish `*foo` (deref) from `(*)foo` (partial application of multiplication) at a language level :(

**Comment by jordwalke** [comment]
I'm not exactly sure if this is launch blocking for the new syntax. I think we can use `.contents` in the mean time and if we come up with something better, we can add it in at that time.

**Comment by let-def** [comment]
I remember this syntax was suggested because it was deferencing syntax from pascal.
It seems much more natural to have postfix syntax for dereferencing (as this works with "method-chaining"), while the prefix syntax from C forces a lot of parentheses.

I don't see why `postfix^` is now a problem? (a part from the implications of having postfix operators).

**Comment by jaredly** [comment]
yeah let's not block launch on this. I agree that postfix seems to make more sense.

**Comment by chenglou** [comment]
Yeah I think this is fine.
