### ISSUE TITLE
`++` is now left-associative

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1500]
Previously, Reason and OCaml's `^` are right-associative. Now it's left-associative. A small consequence of this is that the old snippet:

```reason
a ^ b ^ c
```

now converts to

```reason
a ++ (b ++ c)
```

instead of 

```reason
a ++ b ++ c
```

cc @let-def

**Comment by jordwalke** [comment]
@chenglou If in 1.13.7, it was left-associative, then when converting shouldn't it convert to `a ++ b ++ c`?

**Comment by chenglou** [comment]
I got the left/right wrong. Fixed. The issue's still here though

**Comment by jordwalke** [comment]
FWIW, it appears `^` was actually right associative in 1.13.7.

**Comment by jordwalke** [comment]
Only downside is that `+` is left associative so it would be confusing if `++` was right associative. Maybe it doesn't matter since `++` will nearly always be used for string concat which we know abides by the associative property `a ++ (b ++ c)` is always equal to `(a ++ b) ++ c`.  It would be rare for someone to be bitten by an assumption that `++` was left associative when it's really right associative. Debugging might be a bit unintuitive.

**Comment by jordwalke** [comment]
I'm inclined to vote right associative for `++`.

**Comment by let-def** [comment]
If `++` is left-associative, it has no impact on string concatenation, but if it was overloaded for list concatenation, then a chain of `++` degenerates to a quadratic runtime, whereas a right-associative on is linear.
`++` should be right-associative.

**Comment by ckknight** [comment]
How often and typical is `++` overloaded to be list concatenation?

**Comment by chenglou** [comment]
Done in #1598
