### ISSUE TITLE
Treat type constructors like functions

### ISSUE THREAD

**Issue by cullophid** [facebook/reason#1521]
example 
```
type action =
  | InputChanged string
  | SomeOtherAction string string;


/* Behave like first class function */
<input onChange=(self.reduce InputChanged) ... />


/* should work with |> and currying */
let someEventHandler input => input  |> String.trim |> String.lower |> SomeOtherAction "Event";

```

**Comment by chenglou** [comment]
Try this:

```reason
type action =
  | InputChanged string
  | SomeOtherAction string string [@@bs.deriving accessors];

<input onChange=(self.reduce inputChanged) ... />
```

**Comment by cullophid** [comment]
@chenglou Thanks... though i would argue that this would be better as a language feature

**Comment by ckknight** [comment]
It would be an interesting feature to pass `InputChanged` as a function if it was statically detected to not have all its arguments filled out.

I could see some potential confusion if someone were to accidentally use `Some` instead of `Some ()`, but that's not conceptually different from leaving off a function argument normally.

**Comment by jaredly** [comment]
we now have `|.`, which accomplishes part of this.

**Comment by cullophid** [comment]
@jaredly im not sure why this was closed? `|.` does not really solve this.

**Comment by chenglou** [comment]
You can pipe into variants now, which is what he meant by partially accomplishing this. I guess we can give sugar to `[@bs.deriving accessors]` too, or just have it enabled by default, but that's a bit much
