### ISSUE TITLE
refmt's greedy reformatting causes mistake in punning 

### ISSUE THREAD

**Issue by fxfactorial** [facebook/reason#1750]
Given: 

```
type permissionDetailsLocationIOS = {scope: [ | `whenInUse | `always]};
[@bs.module "expo"] [@bs.scope "Permissions"] [@bs.val]
external _get : 'a => Js.Promise.t('b) = "getAsync";
type permissionResponse = {
  expires: string,
  status: string,
  ios: option(permissionDetailsLocationIOS),
};

let get = permission => {
  let perm = permission |> _to_string;
  Js.Promise.(
    _get(perm)
    |> then_(r =>
         resolve(
           Js.Result.Ok({
             expires: r##expires,
             status: r##status,
             ios:
               switch (Js.Undefined.to_opt(r##ios)) {
               | None => None
               | Some(s) =>
                 let variant =
                   switch s##scope {
                   | "whenInUse" => `whenInUse
                   | "always" => `always
                   | _ =>
                     raise(
                       Helpers.MissingFieldShouldExist(
                         "scope",
                         {j|Error: $s##scope|j}
                       )
                     )
                   };
                 Some(scope);
               /* Some({scope: variant}); */
               },
           })
         )
       )
    |> catch(oops => resolve(Js.Result.Error("Crap")))
  );
};
```

Then you'll see that if we call `let variant` as `let scope` and try to do `Some({scope})`, then refmt will rewrite this as `Some(scope)` and hence code will not compile. 

This is a mistake, it should keep `Some({scope})`.

`Reason 3.0.4 @ 731e605`

**Comment by jordwalke** [comment]
We had a decision to make with what to do with the following: `x => {x}`. Would the returned expression be like any "function body", that returns an `x`, or would it be a single record field punned? We originally decided to interpret, *and print* it as sequence expression that "returns the x". What was the reasoning? Because it's pretty rare to have a single record field since record types aren't extensible - except in the case of a single mutable cell, a single record field is about as good as no record at all.

JavaScript had a similar situation with `x => {x}` would it be a body or a returned record with a punned field? JS decided that it should be a body, and that if you wanted to return a record (punned or not), you must disambiguate by wrapping it in parens `x => ({x})`.

The printer here is currently printing according to spec, and it is showing you more clearly how it is parsing the `{scope}` expression. The suboptimal behavior is in the unintuitive parsing.

**Comment by anmonteiro** [comment]
fixed in master, though the formatting could be better:

```
                 Some(
                   {
                     scope;
                   },
                 );
```
