### ISSUE TITLE
pipe to multiple functions

### ISSUE THREAD

**Issue by zheeeng** [facebook/reason#1988]
Can we have a syntax that reverse-pipe one argument to multiple functions like below? (for reusing argument)
```reason
let (a, b) = 42
    |> ((+)(7), (*)(2));
```
We get `a` as 49 and `b` as 84 ?

**Comment by chenglou** [comment]
```reason
let (a, b) = 42 |. ((+)(7), (*)(2));
```

https://reasonml.github.io/en/try.html?rrjsx=true&reason=DYUwLgBAFAhgNBARgSggXggFgEwQD4B00UA1MlAOzIJQBU52yyA3EA

You can't do this with `|>` because it's treated as a normal infix operator. But [fast pipe](https://bucklescript.github.io/docs/en/fast-pipe.html) works.

(But let's not write too much code this way lol)
