### ISSUE TITLE
Make `rtop` work on windows

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#2167]
@bryphe confirmed that `rtop` works on windows as well! The only part that does not is the little shell script wrapper that forms `rtop` binary. Instead, we should make `rtop` compile a native `.exe` that does the same thing as the script wrapper. This would be a huge unblocker for Windows native Reason, and is relatively easy to implement. We just need the `rtop` directory to have a native executable that achieves the following logic:

This is also a great first task.

```sh
#!/usr/bin/env bash

# Copyright (c) 2015-present, Facebook, Inc.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.


# 0. Touches .utoprc (otherwise utop will fail).
# 1. Avoids "#use"ing ~/.ocamlinit before reason is required.
#    Otherwise, the ~/.ocamlinit is written in `.ml` syntax that will
#    choke the reason parser.
# 2. Add the $HOME directory to the include paths so that in step 3
#     we can actually load the ~/.ocamlinit (but before we require
#     reason).
# 3. Run ml rtop_init.ml that "#use"es ".ocamlinit", and then finally
#    require's reason, so that reason is required after .ocamlinit is
#    parsed in standard syntax.

touch $HOME/.utoprc
touch $HOME/.utop-history
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# intercept the -stdin flag of utop, and preprocess the code into reason code
# before forwarding it. Afaik currently there's no better way of intercepting
# the code after urtop receives code from stdin and before it processes it
if [[ $@ =~ "stdin" ]]; then
    refmt --parse re --print ml --interface false | utop-full $@
else
    utop-full -init $DIR/rtop_init.ml $@ -I $HOME -safe-string
fi

```

**Comment by bryphe** [comment]
In case it helps, here's how I tested on Windows w/o the script:
- `npm install -g esy@0.2.9`
- `git clone https://github.com/bryphe/esy-minimal-rtop-project`
- `cd esy-minimal-rtop-project`
- `esy install` (May need to retry this, due to esy/esy#413 and esy/esy#414)
- `esy build`
- `esy x utop-full -init C:/Users/<YOUR USERNAME>/.esy/3_/i/esy_ocaml__slash__rtop-3.3.0-c101f070/bin/rtop_init.ml -safe-string`
and voila:

![image](https://user-images.githubusercontent.com/13532591/44880606-cfa06280-ac61-11e8-86b8-fc4b54187440.png)

But, once we have the native wrapper - it should be as easy as `esy x rtop` 👍

**Comment by jordwalke** [comment]
@bryphe and once we have the native wrapper, building an `esy release` will expose an npm binary to `rtop.exe`, correct?

**Comment by bryphe** [comment]
@jordwalke - yep! Although, `esy release` is blocked on Windows at the moment by https://github.com/esy/esy/issues/418
