### ISSUE TITLE
Currying breaks generic types.

### ISSUE THREAD

**Issue by seprich** [facebook/reason#2340]
Consider and test with the following code:
```
let test: string => 'a => unit =
  (a, b) =>
    Js.log(a ++ ": " ++ Js.String.make(b));

test("first", 1);
test("second", "kedua");

let t2 = test("Curried");
t2(1);
t2("something");
```
This demonstrates that calling `test` directly with different type 2nd arguments is OK, but calling t2 with integer and string is not accepted by the transpiler:
```
We've found a bug for you!
OCaml preview 11:12-59

This has type:
  string
But somewhere wanted:
  int
```

Is this behavior a bug or a feature? Certainly it surprised me, I would have expected the curried version to have signature of `'a => unit` and accept calling with different types without "collapsing".

**Comment by anmonteiro** [comment]
I think this might be the value restriction at work (https://caml.inria.fr/pub/docs/manual-ocaml/polymorphism.html). You need to eta-expand / not curry if you want the function to remain polymorphic.

BTW, the Reason repo is not really the place to ask these questions, since this is more of an OCaml question anyway - Reason is just a parser / pretty printer, the underlying semantics of OCaml are still preserved.

**Comment by seprich** [comment]
so its a feature, thanks for answering anyway. And before asking I didn't know that this is related to ocaml and not to related to trispiler but thanks for answering anyway.

**Comment by anmonteiro** [comment]
I'd recommend joining the Reason Discord (here's an invite: https://discord.gg/YuhYeh) if you run into similar questions.

**Comment by mlms13** [comment]
Since I've run into "value restriction" quirks a few times, I just wanted to leave this here in case anyone else finds it. In the example above, the following doesn't compile:

```reason
let t2 = test("Curried");
t2(1);
```

But this would compile and work as expected:

```reason
let t2 = v => test("Curried", v);
t2(1);
```

In not-very-technical terms, the compiler treats "things that look like functions" differently from "things that look like values" when polymorphism is involved.
