### ISSUE TITLE
support for visual studio code please

### ISSUE THREAD

**Issue by hdcos** [facebook/reason#480]
would be really great! :) thanks

**Comment by chenglou** [comment]
No one on the team uses VSCode right now so there aren't any support. But I've personally heard really good stuff about it and its perf. Tagging this as community project unless one of us start using VSCode =]/

**Comment by jordwalke** [comment]
Yeah, this sounds like a great community project.

**Comment by nmn** [comment]
If there are tools for Atom, they can be ported over with relatively less work.

**Comment by kayceesrk** [comment]
This seems relevant: https://marketplace.visualstudio.com/items?itemName=hackwaly.ocaml

**Comment by chenglou** [comment]
cc @Schmavery

**Comment by Schmavery** [comment]
Looks like the plugin linked by kayceesrk is what I was making, but finished.  Wouldn't probably be pretty easy to convert to reason.

**Comment by freebroccolo** [comment]
I've started working on a Reason extension for VS Code at [vscode-reasonml](https://github.com/freebroccolo/vscode-reasonml). It's very minimal at the moment and just does some highlighting but it should improve quickly.

**Comment by chenglou** [comment]
Sick. If this becomes established we'll include this (or leave it separate. There's a reason why all the plugins are included in the reason project right now) officially!

**Comment by jordwalke** [comment]
I think a lot of people will like this (especially if you can use the debugger/type interaction from [this plugin](https://marketplace.visualstudio.com/items?itemName=hackwaly.ocaml)).

**Comment by freebroccolo** [comment]
Just to give a status update on this, the vscode extension now supports type-on-hover and completion. I plan to take a look at adding support for the debugger soon.

**Comment by jordwalke** [comment]
Very cool. were you able to reuse a lot from the other VSCode Merlin plugin?

**Comment by freebroccolo** [comment]
@jordwalke well I ended up implementing things a little bit differently in a few places. For example, using merlin protocol v3 and implementing the merlin functionality as a [language server](https://code.visualstudio.com/docs/extensions/example-language-server). The reason extension also does incremental synchronization instead of full synchronization. So I didn't reuse much directly but the OCaml plugin did help me understand several things early on about how merlin works.

The merlin language server part could in fact be drawn out into a separate package now but it might be nicer to port it to OCaml or Reason. But in that case, I think it's the kind of thing that should be distributed with Reason with the other tools so the user doesn't have to compile it on their own.

**Comment by kennetpostigo** [comment]
I think this is good to close, vscode is one of the best supported editors.
