### ISSUE TITLE
[Syntax] changes based upon empirical research

### ISSUE THREAD

**Issue by battisti** [facebook/reason#485]
Should this not already be part of the syntax discussions, would it be possible for arbitrary choices to default on the result on the few empirical studies that have been made in this area?

e.g. 

[Andreas Stefik and Susanna Siebert. 2013. An Empirical Investigation into Programming Language Syntax. ACM Transactions on Computing Education 13, 4, Article 19 (November 2013), 40 pages.](http://dl.acm.org/authorize?6968137)

**Comment by chenglou** [comment]
Nothing immediately actionable here, but this is one of the biggest things Reason enables: allowing us to freely experiment on new syntaxes, empirically, without breaking code. Somewhat related: I myself am a fan of [Koka](http://research.microsoft.com/en-us/projects/koka/), [Red](http://www.red-lang.org) and [Kitten](http://kittenlang.org/intro/)'s syntax. Now we'll actually have a chance to take their best sugars and try them in some future alpha Reason releases for the adventurous ones, while others stay with the stable Reason syntax (or their own flavor of it, who knows...) and keep coding. Exciting future ahead.

However, because there's nothing immediately actionable, I'll close this for now. Thanks for the paper and we'll keep this in mind! =]

**Comment by jordwalke** [comment]
I just read the abstract and it sounds fascinating. One thing to consider is that Reason's goal is to reach out to the majority of industrial programmers, not necessarily first time programmers. Experienced industrial programmers have already become tainted, such that syntaxes that are empirically worse for beginners, may be easier for those experienced people to pick up quickly. I would love to see a similar experiment done on experienced programmers.
