### ISSUE TITLE
What is meant by "Bare metal compilation - No Virtual Machine." in README.md?

### ISSUE THREAD

**Issue by R3D4C73D** [facebook/reason#486]
> Bare metal compilation - No Virtual Machine.

To me, [bare metal](https://en.wikipedia.org/wiki/Bare_machine) means running on computer hardware without an operating system or runtime system.  However, I get the feeling this isn't what is meant in this case.

Also, this is mentioned on the website:

> Reason‘s non-invasive approach to the OCaml compiler allows Reason code to take advantage of all of the existing OCaml compiler optimizations/backends such as bare metal ARM, x86, and even JavaScript compilation.

Other than these two tasty blurbs, nothing is ever mentioned again.  At least, not that I can find.  Can someone please elaborate on what is meant by "bare metal" in these cases?  How might one do this?

**Comment by bsansouci** [comment]
Hey @R3D4C73D!
I think in this case what `bare metal compilation` means is compilation to native code. This means when running the executable you're not booting up a whole VM that's going to interpret bytecode (which ocaml also supports with the [ocamlc](http://caml.inria.fr/pub/docs/manual-ocaml-4.00/manual022.html) compiler).

So OCaml can compile to 
- x86 native code with the [ocamlopt](http://caml.inria.fr/pub/docs/manual-ocaml-4.00/manual025.html) compiler
- ARM native code with, for example, the [ocamlios](http://psellos.com/ocaml/compile-to-iphone.html) compiler
- JS with [js_of_ocaml](http://ocsigen.org/js_of_ocaml/)

Because Reason plugs into the OCaml toolchain, it can benefit from all of those backends :D

**Comment by hhugo** [comment]
This comment probably refers to https://mirage.io/

**Comment by R3D4C73D** [comment]
So we're referring to an executable with a runtime library either linked or statically compiled in, designed to be run on a host operating system?

**Comment by bsansouci** [comment]
If you're talking about Reason then no, it's not a library but merely a new syntax for OCaml and a suite of tools to make the development experience that much better.

**Comment by jordwalke** [comment]
The bullets there are intended to answer the question "why might I be interested in Reason" from the perspective of someone who doesn't know all of the benefits of OCaml.

Our wording is not clear. Let's improve it. Maybe you can help me determine how to describe this. Even if you somehow had a JavaScript VM running without a host OS, would you call that bare metal? I don't think so. I think that bare metal at least requires that there be no heavy language virtual machine between your code and the processor (is that incorrect?) That is the part I meant to focus on, and although you could likely run OCaml (with/without Reason) on a bare metal unikernel or something I think that is too specific for what I wanted to convey, which is that:

Reason is a more accessible *interface* to all the benefits of the OCaml language, which includes the fact that you can run `ocamlopt`, where the generated code does not have a language level virtual machine intercepting and executing instructions. You can gdb and make sense of the generated assembly.

**Comment by jberdine** [comment]
To me, "bare metal" means there there is no OS or anything.  That is, a piece of software that runs "bare metal" includes everything from the boot loader on up.  Perhaps running on a unikernel is close enough, as that layer is pretty thin.

In the interest of being explicit about technicalities, with Reason there is a run time system (garbage collector, signal handling support, wrappers of libc, etc.) but not an interpreter or just-in-time compiler, etc.  Reason code compiles to native machine code, and is linked with the run time system which is also native machine code.  This puts Reason somewhere between C, since the Reason run time system includes a garbage collector, and Java which has a garbage collector as well as a just-in-time compiler.

From this perspective, Reason and OCaml are the same.

**Comment by R3D4C73D** [comment]
Yeah, I'm not sure how best to describe this.  This particular issue is a vernacular minefield.

OCaml and, by extension, Reason programs, even when compiled to run without a virtual machine, still require a runtime library.  That library is built on top of resources provided by the host operating system.  Therefore, these programs can't run without the operating system for which they were compiled.

Some people use the word "compiled", but that ceases to mean much now that languages like Coffeescript and Typescript can be said to be "compiled" to Javascript, although some prefer the term "transpiled".

Some people use the term "systems programming language" for those that can be compiled to run under an operating system but without a virtual machine.  Programs that require virtual machines are often referred to as interpreted, but technologies like JIT compilers muddy the waters.

I apologize if I'm not being helpful here, but this is a very hard topic.  There's no clear (human) language I'm aware of to describe this type of situation.  Maybe that's because 30 or so years ago, this was just the default.

**Comment by kayceesrk** [comment]
Ahead-of-time compilation?

**Comment by jordwalke** [comment]
> Yeah, I'm not sure how best to describe this. This particular issue is a vernacular minefield.

Well said.

>.. Reason programs, even when compiled to run without a virtual machine, still require a runtime library. That library is built on top of resources provided by the host operating system.

But have you seen this? http://www.algo-prog.info/ocapic/web/index.php?id=ocapic

> Ahead-of-time compilation?
@kayceesrk Is it clear in that case that it compiled ahead of time to machine instructions which don't go through an interpreter? One challenge I've had in describing the OCaml compiler is that people cannot wrap their head around a language that looks expressive, with type inference, first class functions, no ceremony around pointer/lifetimes, and yet also compiles ahead of time to bare metal instructions. This does not compute well in most people's minds. The term Ahead of Time (in my experience) leaves room for the interpretation "Oh, it compiles ahead of time into an intermediate representation, a kind of optimized byte code, which is then interpreted at runtime". I'm searching for a term that gets the main point across - that you can look at the assembly for function implementations/field accesses, and make sense of it - instructions don't go through an interpreter and that plain assembly doesn't need to be generated by a JIT.

**Comment by kayceesrk** [comment]
@jordwalke From my understanding, ahead-of-time compilation is a term specifically invented to distinguish compilation to machine code for languages which typically run under a JIT (CIL, Java Bytecode, etc). Before the advent of JIT, languages were either interpreted or compiled natively possibly linked with a C runtime. The wikipedia page on AOT compilation is quite clear in its explanation, with useful links to other compilers [0]. But if you want to remove any ambiguity, perhaps "ahead-of-time compilation to native machine code", but this is not as catchy as AOT or bare-metal. 

[0] https://en.wikipedia.org/wiki/Ahead-of-time_compilation

**Comment by jordwalke** [comment]
Thanks.

**Comment by jordwalke** [comment]
Improved README. Reopen if needed: https://github.com/facebook/reason/commit/29457d7b261bed4b9f066e8fb4684aa42cecf9ff
