### ISSUE TITLE
Syntax for pattern matching on lists

### ISSUE THREAD

**Issue by jayelm** [facebook/reason#488]
Right now, both of these work:

```Reason
let head = fun lst => switch lst {
  | [] => failwith "Empty list"
  | [hd, ...tl] => hd
};

let head = fun lst => switch lst {
  | [] => failwith "Empty list"
  | hd::tl => hd
};
```

Is this by design? Since `item1 :: item2 :: rest` has been replaced by `[item1, item2, ...rest]`, it seems like sticking to the latter syntax while pattern matching is the more consistent option.

**Comment by jordwalke** [comment]
Good call. We must have merely not deleted this parsing rule yet. Feel free to send a PR to remove it.

**Comment by modlfo** [comment]
Hi!
Among all the syntax changes, this is the only one I did not like. What seems odd for me is that the "..." is used as well in records "{...a,  }". My suggestion is to use the "..." only in one of the contexts. 

It would be interesting to know the motivations behind this syntax change.

**Comment by yunxing** [comment]
@modlfo Good question! 

When I first saw the syntax, I feel it is pretty intuitive. I think `...` as "expand" operator.

In the case of `[hd, ...tl]`, I interpret it as "expand list `tl`, add `hd` in front of it"

In the case of `{...a, }`, I interpret it as "expand record `a`, modify certain fields of it"

**Comment by jordwalke** [comment]
Hi @modlfo: It's good to hear you found the rest of the changes helpful/preferable. This is the syntax used by JavaScript for Array and object(record) "spreading". That syntactic pattern `...` represents "that other thing, but with these things added".
The reasoning was that it doesn't matter too much what they look like as long as they have no syntactic pitfalls and were somewhat easy to learn.
I don't really love them, personally (I just find three dots `...` a little annoying to type), but I find like that more people can instantly recognize them in my code even without having to learn a new language.

I like this better fwiw, do you agree?

```
let r = {myRecord | nextField: "hi"};
let a = [head | tl ];
```

**Comment by modlfo** [comment]
Hi @yunxing that's exactly the case (`[...tl, hd]`) I was thinking that it can be confusing with `...`

Since I'm more familiar with OCaml and F# I have a strong preference for the cons operator `::` to create and pattern-match lists.  `h :: t` is more compact than `[ h, ... t ]`.

@jordwalke using `|` in my opinion looks nicer and one has to type less. In addition, it's not possible  to write `[ | t, h ]` as in `[...tl, hd]`. In the case of records, `{myRecord | nextField: "hi"}` looks quite nice for me.

**Comment by radekm** [comment]
Currently I don't like the Prolog version `[head | tl ]` very much - at first glance it looks like a polymorphic variant from OCaml (BTW does Reason support polymorphic variants?).

**Comment by yunxing** [comment]
@radekm We do support polymorphic variant with the same syntax. It actually took us a lot of efforts since there are many edge cases of syntax that we don't even know what the semantics are.

We chose not to document it in the basic syntax so we don't scare people away : )

**Comment by jordwalke** [comment]
>  that we don't even know what the semantics are.

@Yunxing is referring to "intersection types", which many people don't know even exist in OCaml. But we support parsing and print of them because we want to maintain a complete mapping of the entire language.

**Comment by nmn** [comment]
I would like to jump in and say that I like the `...` spread syntax from JS the best in terms of readability.

That said, I prefer consistency over anything else. The `...` syntax is consistent across lists and records.
But on the down-side, `[...head, tail]` being illegal is a little annoying. But that seems like a problem in OCaml itself, and so I'm not sure it can be solved with syntax.

**Comment by bsansouci** [comment]
I agree with @nmn, the consistency is important even at the cost of "more characters to type" when matching on `[head, ...tail]` instead of `head::tail`. Also `[head | tail]` is confusing coming from lower level languages where `|` is bit-wise OR.

**Comment by jordwalke** [comment]
@nmn, may I ask, is your background web/JavaScript development? Have you used other functional languages such as OCaml (I ask because it helps us keep track of which suggestions/preferences come from which "groups" of people). So far, quite predictably, people from JS web background resoundingly favor syntactic forms that resemble ES6 (I suppose this wasn't that difficult to predict).

fwiw, `[...list, appendOne]` could be made to represent `List` concatenation. Even `[...list, insertOne, ...tail]` could be made to work. This obviously couldn't work for pattern matching, but could work with expressions. The one downside is that it does encourage order `n` operations on lists.

**Comment by nmn** [comment]
My background is in the Javascript community. That said, I keep learning languages. I have some experience with Haskell, Elm, and Purescript.

So, while of course, I have my own bias, I'm trying to be objective whenever I comment on an issue.

**Comment by jordwalke** [comment]
@nmn. Cool, just trying to understand where you're coming from. I'm somewhat like you in that I try just about every new language.

**Comment by jberdine** [comment]
I'm open to many of the proposals for pattern matching syntax, but I for one would not welcome pattern matching syntax that cannot be compiled efficiently.  "Efficiently" probably needs to be clarified, but I would say not more than a few branches (linear in the number of cases with a small constant), and preferably no allocation.

**Comment by jordwalke** [comment]
@jberdine We are in total agreement - the slower operations would not be pattern matching, they would be expressions that represent concatenation (exactly the same as if you had written `List.concat ..`).

**Comment by bsansouci** [comment]
After a discussion with @schmavery, we've reached the conclusion that even though `...` isn't perfect, it's a good choice considering the tradeoffs (familiarity, power, visual representation of expression vs pattern matching, reasoning simplicity). That said, using it for both records and lists might not be necessary. We currently don't support `[...rest, a]` or `[a, ...rest, b]` because they're implicitly linear time. This makes `...` act pretty differently on lists (differently compared to JS and compared to reason records). So I'd be in favor of bringing `::` back for lists, which is nice and consistent across the board, and keeping `...` for records.

**Comment by nmn** [comment]
That makes sense to me.

**Comment by jordwalke** [comment]
> We currently don't support `[...rest, a]` or `[a, ...rest, b]` because they're implicitly linear time.

We _could_ trivially for list concatenation, making them more consistent with the JavaScript syntax. The primary value of the `...` syntax is just that they're immediately recognizable by the largest programming community in the world. I don't even particularly love them, but I love that just about anyone can immediately pick up on what they represent which means code I write will be understood by more people, and more people can benefit from OCaml more quickly.
When I was learning OCaml, it took me a little white to understand infix operators that weren't the traditional `+/-` etc because it wasn't obvious what the parsing precedence was:

```rust
myFunc a b :: myFunc c d
```

It took me a little while to understand that it was never parsed like:

```rust
myFunc a (b :: myFunc) c d
```

Now that I've been knee deep in the yacc parser for a while now, I understand fully, but I'm trying to put myself in the shoes of a noob. There's a ton of interest in Reason specifically because it makes an effort to appeal to a wider audience. If there's anything that's more familiar and we can tolerate it, we should opt for it, especially since we know we can always fix it later and auto-upgrade peoples' code using `refmt`. If the only thing accomplished by Reason is that we had gotten more people to use OCaml in its current *exact* form, but had to go through the process of casting a net with an approachable syntax and bringing it back closer over time - then it seems like a win to me.

We don't want to be familiar just for the sake of familiarity - there are some things that I think we should do just as ML has done, but this one isn't quite as clear so that makes me lean more towards widespread familiarity - we can always change our minds later.

**Comment by bsansouci** [comment]
@jordwalke thanks for explaining. `...` everywhere does make it more readable. Time will tell if JS folks can't unlearn `[...rest, a]` ;p

**Comment by hcarty** [comment]
"unlearning" differences in syntax is an argument for making different things look different.  This comes up a few places in Reason - `...` in lists, `switch` for pattern matching both come to mind.

**Comment by jordwalke** [comment]
IIRC, Swift not only used the keyword switch, but even went as far as to require huge ugly "case" tokens before each match. IMHO that's taking it too far, but I do see the benefit of making things familiar even if it's a new concept. It's the difference between "here's an entirely new concept" and "switch statements are better than you are used to in other languages".

**Comment by yunxing** [comment]
I'm closing this now as the concern of the original poster has been resolved. Feel free to reopen this one or continue discussing about what syntax should we use here.
