### ISSUE TITLE
Release Atom `js_of_ocaml` bindings as a library

### ISSUE THREAD

**Issue by smondet** [facebook/reason#529]
There is a lot of generic code there:
https://github.com/facebook/reason/tree/master/editorSupport/atom-reason/src

That could be a pretty useful library :)

**Comment by jordwalke** [comment]
That's true, it would be cool. I only hesitate because we see that as an implementation detail that we may massively change and I'm sure we would upset people. When it stabilizes, it will be a better time. There are also existing node bindings that we should be using for a portion of the functionality. Closing just to clear up the task queue but please feel free to continue to discuss here.
