### ISSUE TITLE
Remove LBRACKETATATAT and LBRACKETATAT

### ISSUE THREAD

**Issue by SanderSpies** [facebook/reason#544]
Instead of [@], [@@], and [@@@], we can just have [@].

(via @jordwalke on Twitter - didn't see an issue for it yet).

**Comment by hcarty** [comment]
Is this for attributes? I think the main thing this change would introduce is lots of extra parens in your code to help specify scope since [@], [@@] and [@@@] all apply to different syntactic elements.

**Comment by jordwalke** [comment]
One of the benefits of having consistent delimiters in Reason is that now we can achieve this without extra parenthesis.

**Comment by hcarty** [comment]
How do you attach attributes to variant types vs variant constructors?

**Comment by jordwalke** [comment]
There are a few options I see. Here's one proposal:

```rust
[@@deriving baz]
type t =
  [@foo]
  | A
  [@bar]
  | B;
```

I had made good progress towards this previously, but was blocked when concepts such as "zero or more leading attributes" ended up generating misleading locations in the event that there were zero leading attributes. Since I last tried, we switched to Menhir, which solves this problem so it's worth reviving.

**Comment by hcarty** [comment]
That still has `@@` though - I thought the proposal was `@` everywhere?

Putting attributes before each variant constructor is very strange coming from OCaml.  In general it seems counter-intuitive to put attributes before the actual thing be marked up.  That may be a long OCaml background talking though.

**Comment by jordwalke** [comment]
Also, since we want to preserve the lack of white space sensitivity, then the we must acknowledge that the ability to simplify ppx syntax like this, is made much easier by consistent delimiters. If we end up removing delimiters such as `;`, then this will be much more difficult to accomplish (though maybe still possible).

**Comment by hcarty** [comment]
If variants were wrapped in `{}` then a suffix position could work for `@`-only attributes:
```ocaml
type t = {
  | A [@onA]
  | B [@onB]
} [@ont];
```

**Comment by hcarty** [comment]
The following could work without immediately apparent ambiguity if `;` sticks around:

```
[@module_level_attribute];
type t = {
  | A (int [@argument_attribute])
  | B [@constructor_attribute]
} [@type_attribute];
```

**Comment by chenglou** [comment]
![what the do you want _0c9bd492208d3deed49aa752f41c4698](https://user-images.githubusercontent.com/1909539/30446401-e79d2c16-993d-11e7-94b4-ea72d985f43e.png)

Done
