### ISSUE TITLE
Can't have a variable named `end`

### ISSUE THREAD

**Issue by frantic** [facebook/reason#603]
Couldn't find anything in the docs about this.

![image](https://cloud.githubusercontent.com/assets/192222/16293446/c203d246-38ce-11e6-90e9-7b97c35fbb87.png)

**Comment by cristianoc** [comment]
@frantic looks like `begin` and `end` are still keywords, though they are unused in Reason.

**Comment by cristianoc** [comment]
Unless there's some plan to use the keywords for something yet to come, they can just be removed.

**Comment by SanderSpies** [comment]
Good first bug?

**Comment by yunxing** [comment]
We didn't remove unused ocaml keywords in reason. The problem is that if you
named a variable as "end", in the future when we format it ocaml, it will
create a syntax error as "end" is revered in reason.

  

If this is a real problem, I think we can 1) provide a friendlier error
message 2) use our operator swapping infrastructure that swaps 'end' to
something like "\end" in OCaml.

  
\--

Yunxing

  

![](https://link.nylas.com/open/2gjtyq1vxam8jgrgiizrfc7pl/local-
309505c0-f8df?r=cmVwbHkrMDAwZjg3NTkzNTU0ZmU0N2M2NzFkM2I5ZjI4NzIwOGMzMGI0Y2JiYWFjMTMwMDc0OTJjZjAwMDAwMDAxMTM4MzUwMmM5MmExNjljZTA5YTU5OGY4QHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 23 2016, at 12:22 am, Sander &lt;notifications@github.com&gt; wrote:  

> Good first bug?  
>  On Jun 23, 2016 08:50, "Cristiano Calcagno"
&lt;notifications@github.com&gt;  
>  wrote:  
>  
>  &gt; Unless there's some plan to use the keywords for something yet to
come,  
>  &gt; they can just be removed.  
>  &gt;  
>  &gt; —  
>  &gt; You are receiving this because you are subscribed to this thread.  
>  &gt; Reply to this email directly, view it on GitHub  
>  &gt;
&lt;https://github.com/facebook/reason/issues/603#issuecomment-227964676&gt;,  
>  &gt; or mute the thread  
>  &gt;
&lt;https://github.com/notifications/unsubscribe/ABEABbZpSaRpIHGe48KSmR4k_WHUA8aAks5qOiyxgaJpZM4I8fDr&gt;  
>  &gt; .  
>  &gt;  
>

>

> —  
> You are receiving this because you are subscribed to this thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/facebook/reason/issues/603#issuecomment-227970297&r=cmVwbHkrMDAwZjg3NTkzNTU0ZmU0N2M2NzFkM2I5ZjI4NzIwOGMzMGI0Y2JiYWFjMTMwMDc0OTJjZjAwMDAwMDAxMTM4MzUwMmM5MmExNjljZTA5YTU5OGY4QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe/AA-
HWUajWT_ShFZPCE8tTLh4RnCB0_Rqks5qOjQsgaJpZM4I8fDr&r=cmVwbHkrMDAwZjg3NTkzNTU0ZmU0N2M2NzFkM2I5ZjI4NzIwOGMzMGI0Y2JiYWFjMTMwMDc0OTJjZjAwMDAwMDAxMTM4MzUwMmM5MmExNjljZTA5YTU5OGY4QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/AA-HWcJZor1FAiOr8Z_1Xb2BZ5feG2WQks5qOjQsgaJpZM4I8fDr.gif)

**Comment by cristianoc** [comment]
@yunxing we definitely want to preserve the property that programs written in Reason are representable in OCaml, and the other way round.
I think going in the same direction as for operator swapping is a reasonable compromise.

**Comment by yunxing** [comment]
Just notice the format my previous reply is totally broken.
