### ISSUE TITLE
Type hints display error in Atom

### ISSUE THREAD

**Issue by liweijian** [facebook/reason#663]
I used atom to read the code of Infer, and it shows as:
<img width="785" alt="screen shot 2016-08-08 at 5 36 56 pm" src="https://cloud.githubusercontent.com/assets/19320783/17475883/d0db0934-5d8f-11e6-9046-797c099736ee.png">

My packages:
<img width="719" alt="screen shot 2016-08-08 at 5 38 34 pm" src="https://cloud.githubusercontent.com/assets/19320783/17475917/e33f6552-5d8f-11e6-8f67-9711470843ac.png">

**Comment by chenglou** [comment]
Weird, I'm getting this too now. What's your Atom version? Do you remember when it was last good?

**Comment by chenglou** [comment]
Turned out this is a known problem with Atom 1.9+
https://github.com/facebook/nuclide/issues/659
I'll leave this issue open until it's solved at nuclide's side. In the meantime, please use the suggested fix [at the end of the issue](https://github.com/facebook/nuclide/issues/659#issuecomment-238198585). Thanks!

**Comment by chenglou** [comment]
Taking things in our own hands!
