### ISSUE TITLE
[parser] Nested object type error

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#707]
Repro:

```
type foo = <
bar : <a: int>>;
```

This works:

```
type foo = <
  bar : <a: int>
>;
```

**Comment by pvolok** [comment]
The problem is that `>>` is being lexed as a token `INFIXOP0(">>")` while the parser expects `GREATER GREATER`.

One idea I had is to lex `>...` to something like `GREATER_WITOUT_SPACE_AFTER ...` and treat it as an operator beginning when we expect operator. But this would also require changing precedence rules.

I will not tackle this issue now as I first need to learn menhir and ocaml operators better. So posted it in case someone takes it.

**Comment by yunxing** [comment]
Another idea is we can build some utilities in our parse to "split" a token into two:
In the lexer, 
  when we see ">>", we tokenize it as two tokens ["GREATER", "GREATER"]. 

In the parser when we see, 
  when we see GREATER GREATER, we reduce them to INFIXOP0(">>"). 

The benefit of doing this is we don't need create fake tokens like "/><" in JSX. As it will be split as ["/", ">", "<"] correctly. Do you think this can make your JSX diff easier ? @SanderSpies @jordwalke

**Comment by yunxing** [comment]
C++03 actually has the same problem, which took people a while to fix: https://en.wikipedia.org/wiki/C%2B%2B11#Right_angle_bracket

**Comment by jordwalke** [comment]
Yeah, Ideally we'd split the tokens into two when possible.

In this case of objects, I was hoping that when we revised the method dispatch syntax, we could also improve the object type syntax. Right now, Reason improved the "class type" syntax but not the object type syntax.

Taking a step back: OCaml has a syntax for object types (which we're seeing here with the `<>`) and a syntax for class types (which look like `object method blah: int -> int end`). In Reason, we've improved the syntax for class types (which you can see in our `oo.re` test file) so that it looks like:

```rust
 {method x : int; method y : int;}
```

I think that we can continue to not only improve that syntax, but also make it so that *object type* syntax is identical. I don't know why OCaml has different syntax for class types vs. regular object types and it's part of the reason why I think no one uses objects in OCaml. After doing some deep exploration of the syntax of objects, I think it's possible to unify class types and object types *syntactically* while always being able to keep the distinction in the AST, once parsed.

All that to say - I think the `>>` issue would go away, but we should still consider breaking it into multiple tokens if possible.

**Comment by jordwalke** [comment]
Alternative proposals:

```rust
/* Hey look, rust syntax highlighting already supports the pub keyword */
let myObject ={
  pri somePrivateMethod () => (),
  pub add one two => one + two,
  pub subtract one two => one - two
};
type typeOfThatObject = {
  pub add: int => int => int,
  pub subtract: int => int => int
};
/* Hey look, how about we unify class type syntax! */
class type typeOfThatObject = {
  pub add: int => int => int,
  pub subtract: int => int => int
};

let result = myObject.add: 10 20;
```

**Comment by SanderSpies** [comment]
@yunxing curious to know how you want to do this - from what I understood this is not possible in the lexer. If it is somehow possible, I would definitely like to know.

**Comment by SanderSpies** [comment]
@jordwalke I like your proposal for objects, but I wonder if we don't make objects too light compared to records this way.

**Comment by jordwalke** [comment]
@SanderSpies : You're thinking there's a downside to making objects *too* lightweight? It encourages their use?

**Comment by SanderSpies** [comment]
@jordwalke - I'm more afraid of over use, but perhaps I shouldn't be.

**Comment by jordwalke** [comment]
It's a legitimate concern. Objects do not perform as well as records.

**Comment by chenglou** [comment]
Ok. Now that the new record syntax is in. We can close this. Should we revert #708 too?

**Comment by chenglou** [comment]
Fixed.
