### ISSUE TITLE
Contributor environment on npm 

### ISSUE THREAD

**Issue by yunxing** [facebook/reason#753]
For contributors that only have npm installed on their machine, we should provide a good contributor environment / workflow for them.

**Comment by jordwalke** [comment]
Agreed.

**Comment by yunxing** [comment]
Here is the proposed workflow: 

# setup
```
git clone https://github.com/facebook/reason # skip this if you already have reason cloned
git clone https://github.com/reasonml/reshell
cd reshell
npm link ../reason # link local reason 
npm install # install dependencies
npm link # link commands globally
```

# Before start hacking
Use `rebash` or `refish` or `rezsh` to pop up a shell with correct environment: 
![image](https://cloud.githubusercontent.com/assets/1017689/18454320/6fa0d64c-78f8-11e6-8887-cfde85ddcb69.png)

# Hacking
... open up editor and hack on reason codebase ... 

# Test changes
In reshell:
```
[RE]~/reason$ reason-test
```
This runs our test suites:
![image](https://cloud.githubusercontent.com/assets/1017689/18454382/cafe9182-78f8-11e6-958b-ee980dec0d53.png)

# Install change
Reinstall change so we can use it in current shell session:
![image](https://cloud.githubusercontent.com/assets/1017689/18454412/0e9df0e0-78f9-11e6-9856-d8745b728672.png)

This is similar to `opam update reason`

# Test changes with rtop
In reshell:
```
[RE]~/reason$ rtop
```
This runs the newly installed rtop from Reason
![image](https://cloud.githubusercontent.com/assets/1017689/18454397/e23d6cba-78f8-11e6-8851-3071c0d1be93.png)

# Test changes with refmt
This runs the newly installed refmt from Reason
![image](https://cloud.githubusercontent.com/assets/1017689/18454446/49dca106-78f9-11e6-9845-b98a203673de.png)

**Comment by jordwalke** [comment]
I think that the install can be simplified a bit:

### Clone and Build Reason

```sh
git clone https://github.com/facebook/reason # skip this if you already have reason cloned
cd reason
npm install # install dependencies
```

### Use A Shell With The Built-in Reason
```sh
npm start
```

Where the Reason's `package.json` has a run script called `"start"` that opens up `reshell`. (Note that `npm start` is a special short command that just calls `npm run start`).

As you've already suggested `reshell` would print the available commands etc and provide some help.

### Hacking

Once in the `reshell` opening up your editor from the command line (`atom src/reason_pprintast.ml`, or `mvim src/reason_pprintast.ml`) will correctly have your path set to include merlin and ocaml and Reason etc.

Running `make`, as always would rebuild `Reason`.

### Top Level
Once in the `reshell`, the `rtop` command correctly opens the top level.

### Top Level
Once in the `reshell`, the `refmt` command is available.

### Install Changes
There wouldn't be a need to do anything to install changes. The moment a rebuild succeeds, the environment is already set up with the path to pick up those changes.

**Comment by jordwalke** [comment]
`reshell` can be a general purpose dependency of `reason`, which can be included in any project (including a web app etc), which:

- Always provides information about the current `Reason` installation for your top level project.
- Prints interesting environment variables ("Is your debug flag set? Are stack traces enabled?).
- Has a couple commands available for enabling environment variables and then writing those to your `package.json` so that they are saved. 
- It can poll your dependencies and continuously check them, giving you a status for when things are not updated or not built correctly.
- Your project itself could even add some extra stuff in `package.json` that `reshell` understands. For example, you can have messages that will be printed in the `reshell` prompt when people type `npm start`.
- Could show a warning icon when you are not in the directory that the sandbox is located at. (Sometimes you want this, but it's easy to forget where you are and which sandbox you're using).
- It could be common for everyone to reserve their `npm start` command as `"start": "reshell"`.
- All of these features could always be executed one-off without entering a shell, simply by doing `npm run editor` etc. The `create-reason-app` scaffolding could make sure your `package.json` has all the common items of `reshell` as npm `run` commands.

**Comment by jaredly** [comment]
Do you think that the common case will be to have this virtualenv setup? It seems that it would only be useful when you're using a custom build of reason, or hacking on reason itself.
everything else that a virtualenv typically provides is covered by us having isolated dependency trees via npm & rebel.
And if we want `reshell`, why not just have the command be `rebel shell`? consolidate our tools, not create too many top-level commands for people to memorize

**Comment by yunxing** [comment]
`rebel` can point to `reshell` when it has the plugin functionality. I'm actually thinking to put more commands into top-level once people is in a shell (how to enter the shell could be anything we discussed, like `npm run shell`, `reshell` or rebel `shell`). 

It would be very easy for people to extend the virtual shell by just writing a toplevel command and have the correct package.json setup (like adding to the ".bin" field or have dependencyEnv with PATH pointing to the command). This command will be guaranteed to run in the correct env environment. 

Here is an example: Someone wants to build a package `list-deps` to list all available ocaml libraries in the virtual environment. The instruction of that package can just say: 
```
## setup
In your devDependencies, add `list-deps`.

## usage
In a virtual shell, type `listDeps`
```

Without a virtual shell, the instruction will become:
```
## setup 
In your devDependencies, add `list-deps`.
In the "scripts" field of package.json, add `"list-deps": "eval $(dependencyEnv) && nopam && listDep"`

## usage
`npm run list-deps`
```

Manually editing `package.json` or `opam` file is something I would like to avoid doing for every projects.

**Comment by jaredly** [comment]
huh, so this "virtual shell" essentially does `eval $(dependencyEnv) && nopam` and sets up some aliases for you?

**Comment by yunxing** [comment]
@jaredly right

**Comment by jordwalke** [comment]
And it could possibly print (or even keep an updated region of the terminal reserved for) a dashboard / smaller toolbar of various things:

- Status of your dependencies (are there any missing in the sandbox or any out of date).
- Is your `rebel` build clean?
- Any background builds/installs in process? (I was thinking when we install a project/sandbox, some of the dependencies can be deferred.
- Maybe list of top `n` errors from last build attempt.
- I've always wanted the ability to push important messages to users of my packages, without them explicitly downloading anything. So maybe we could check your github URL's branch `#notices`, and display those too.
- Maybe we could allow dependencies of your project sandbox to have a field that specifies what to show in a "panel" in the dashboard.

The benefit of a welcome screen/dashboard is that it might show you things you wouldn't think to check yourself.

One question is, for all the fun/fancy stuff, do we want to show it in a terminal? Maybe at that point we should just write to a page and allow that to be opened (it would live update itself all the time). I think the problem with that is no one would check it, so having it automatically show in the shell could be valuable.

I don't think *I* would ever use a shell mode (I'd always just prefix commands with `run`), so I'd also want a way to peak at the dashboard even if not firing up `reshell`. Kind of like how I obsessively run `git status` to remind me of my work in progress.

Check out how cool the terminal can be: You can even use `React` to make terminal UIs https://github.com/Yomguithereal/react-blessed

Only thing better would be if someone made a web backend to `react-blessed` so that we could also use it as a custom pane in our `Atom` `Reason` plugin.

**Comment by yunxing** [comment]
I like the idea showing a dashboard on the terminal. Asking an page has too many hassles in remote development workflow. 

One thing I like about shell mode is the ability to extend -- writing a plugin for the shell mode is just as easy as writing any executables in bash. Also, as people upgrade their `reshell` to a newer version, new commands will naturally be available to them. 

If we don't use shell mode, we need to think about a better way to prompt new commands to users rather than telling them "hey we have a new dashboard command that you can try out, could you update `package.json` for your projects to add ```"reason-dashboard": "git://github.com/reason-dashboard"``` to `devDependencies` and add ```"dasbhoard": "eval $(dependencyEnv) && reason-dashboard"``` to `scripts` field"? 

Another way to achieve this is to have a global toplevel command `re` that automatically deals with package.json. We can also brainstorm about that.

**Comment by jaredly** [comment]
esyyyyyy
