### ISSUE TITLE
Virtualenv for Reason

### ISSUE THREAD

**Issue by yunxing** [facebook/reason#763]
Sandboxes have been generally considered as a more predictable way to develop software. As we are encouraging people to install reason through sandboxes, we could also provide a good shell virtual environment for developers to use. 

A virtualenv (idea borrowed from python), is basically a shell session that has augmented environment variables of a sandbox (for example, if `reason` is installed in a sandbox, the virtualenv session will have its PATH variable pointing to reason so `rtop` is available in commandline).

The virtualenv will also contain utilities to manipulate the sandbox, such as rebuilding a specific dependency. In the future, virtualenv can become a layer of indirection to communicate with underlying package management systems, including `opam` and `npm`

As an example, https://github.com/facebook/reason/issues/753 has been my first attempt to create such a virtualenv, please try it and give some feedbacks.

There could be different entry points to a virtualenv: In python's implementation, one has to directly source a bash file into its current session; in #753 a script is executed to pop up another shell; we have also tried to add a field in package.json/scripts so one can run `npm run shell` to fire a shell.

Like python's implementation, a virtual shell should also have an augmented shell prompt so people are always aware that they are inside a virtual environment and thus avoid certain operations that would pollute the global environment (preferably no global environment exists if everything is installed through sandbox)

**Comment by freebroccolo** [comment]
I was under the impression that there is an `opam local` command being worked on that would do something similar to this in the sense that it would allow you to have path-local switches. How would this proposal interact with that feature?

**Comment by jordwalke** [comment]
@freebroccolo Hopefully the two will converge and the only thing that would change is the `npm start` command that has you entering the shell. I'm guessing that the new local opam stuff has a command for running a one-off script with the opam local switch environment set like `lopam which ocamlc` (which prints the local switch's `ocamlc` location).

So far, the main difference that I see is that with the `npm` sandboxes:
- With the `npm` sandboxes, there is no global artifact, and deleting the directory deletes the sandbox.
- `npm` sandboxes allow installing multiple versions for the same package (which is good for dev dependencies because your project can depend on `reason-1.01` while a dependency can depend on `reason-2.01` - since their only purpose is at build time.
- `npm` supports symlinking of packages (not very well for `git` dependencies though - it overbuilds, so we might have to make our own implementation of the linking workflow). 
- `opam` and  `npm` both have many great features, that the other doesn't have yet. I hope `opam` will eventually get `npm`'s features. (I also miss many of `opam`'s).
- With `npm`, there's no difference between a compiler as dependency and a regular dependency.
- `npm`'s workflow allows a package to declare an arbitrary git url as a dependency.
- There is no manual review for `npm` publishing (obviously true for `git` dependencies, but even for officially published `npm` packages). This means that you can publish packages instantly and people can immediately start depending on them.
- I think we've discovered a subset of features that works on both, and we've built a way to port from `opam` to `npm` for this subset (it was enough to compile all of core, each piece as an `npm` dependency).


That's just a summary of the differences, not a justification for supporting `npm`. There are many things that `opam` does better, in fact. A *justification* is that we are building IDE tooling on top of the `Atom` ecosystem, which uses `npm` as its dependency management system - we want to build that tooling in `Reason` itself. Also, many companies have `npm` support on network disconnected continuous integration hosts, but no `opam` support sadly. `npm` has a workflow that allows downloading the resources, uploading them to `CI` hosts, and then resuming the build (the source download and install are isolated processes). (`opam` might also have support for that, but at least two important companies interested in `Reason` (Facebook included) don't have `opam` support on hosts sadly.

**Comment by jordwalke** [comment]
It would be cool if `opam` supported the ability to download sources (without building), and then also generate an opam-less shell script that would build all of those sources using the opam conventions.

**Comment by jaredly** [comment]
esyyyyyyy
