### ISSUE TITLE
Some comment syntax to reflow comment on refmt

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#900]
Because I don't wanna reflow my comments manually or using a plugin anymore =)

We can't reformat all the comments because some of them have e.g. ascii diagrams or certain formatting people don't want disturbed.

**Comment by jordwalke** [comment]
I would love this. The last manual editing I perform is comments.

It's pretty easy to do this because there already are conventions for expressing parts of comments that should remain untouched (such as markdown code samples which are embedded with four indents). Actually markdown might be a good comment syntax to format according to (at least the formatting portions (such as lists and paragraphs and code samples))

The challenge is not pulling in a huge library! Perhaps we can use an existing one and vendor it.

**Comment by jordwalke** [comment]
Superseded by [this task](https://github.com/facebook/reason/issues/2392).
