### ISSUE TITLE
Vendor menhir

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#979]
This should improve build time a bit (even if we're waiting on esy). @yunxing what are the implication of checking in menhir's file? What else can we remove from the deps?

@bobzhang

**Comment by bobzhang** [comment]
Note you only need check in menhir runtime which is just a single pair of files

**Comment by yunxing** [comment]
There are something more we can vendor: 

[ ] Menhir
[ ] CMDliner 
[ ] EasyFormat

**Comment by anmonteiro** [comment]
I think this is not needed anymore – I recently submitted #2222 to remove vendored libraries and build times are not impacted (I think due to dune).

**Comment by jordwalke** [comment]
We can close and reopen a new discussion around this if you like. We don't need to vendor Menhir, in order to get the benefits of vendoring Menhir. What you can do with Menhir (if you pass the right flags and build commands for Reason repo) is you can remove Menhir as a dependency entirely - making it only a dev-time dependency. It would spit out a plain .ml file for the whole parser, and then we would just publish that plain .ml file, removing Menhir as a dependency. I've heard this is possible. Rudi could probably suggest an approach.
