### ISSUE TITLE
Consider bspack

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#982]
I believe @jordwalke was interested in bspack's approach of bundling everything into a single file for distribution. This might work out for the community too but we'd have to dogfood it first.

We might have to our easy-format into a submodule (we made a fork of it anyway) to make it work with bspack. There are other benefits of this approach too; I'll let @bobzhang comment on this.

cc @yunxing

**Comment by bobzhang** [comment]
The major benefit:
1. Significantly low installation time from 5m to 30s
2. Easy windows support 
If this is agreed on, in the future BuckleScript driver can absorb reason which means
1. Playground for reason too
2. Even faster build - no external process spawned

**Comment by bsansouci** [comment]
Could we also pre-run the ppx?
If our build system makes a distinction between a `devDependency` ppx and a `dependency` ppx, it would know to pre-run a `dependency` ppx on publish, but _not_ pre-run a `devDependency` ppx.

cc @Schmavery

**Comment by bobzhang** [comment]
Ppx is another general issue , maybe we can discuss it in another thread?

**Comment by chenglou** [comment]
We do this now =D. Just need to get this into the main workflow.

**Comment by jordwalke** [comment]
What would we be bspack'ing for Reason in the main workflow?
I would be interested in using bspack for each individual opam library such as `reason`, `rtop`, `flow` etc, where each library contains all its own source files in one giant packed ML. We would likely not pack each packages' dependencies into that same pack, because that could represent a recompilation of those dependencies that will likely already be compiled outside of that pack anyways (so it actually would increase total time I think).

Still, I think it's a great idea for each individual package because you can publish the package's modules to opam as a bspack which saves nearly all file system access and build logic when compiling on the target host. I think it would make a good convention that all build systems in the ocaml ecosystem could make use of. The only thing I'm not clear about yet is how module aliases play with it. Module aliases allow a special limited form of circular dependencies (only in namespacing, not in actual module access).


```reason
/* MyPack.re */
module A = {
};

```
